export const APP_CONFIG = {
  APP_NAME: 'Trello Clone',
  DEFAULT_BOARD_ID: 'default',
  COLUMN_MIN_WIDTH: 272,
  CARD_MAX_DESCRIPTION_LENGTH: 500,
  MAX_CARDS_PER_COLUMN: 100,
} as const;

export const DRAG_CONFIG = {
  DROP_THRESHOLD: 50,
  ANIMATION_DURATION: 200,
} as const;

export const VALIDATION_CONFIG = {
  MIN_PASSWORD_LENGTH: 8,
  MAX_EMAIL_LENGTH: 255,
  MAX_BOARD_TITLE_LENGTH: 100,
  MAX_COLUMN_TITLE_LENGTH: 50,
  MAX_CARD_TITLE_LENGTH: 100,
} as const;
